CREATE TABLE IF NOT EXISTS FLAGS(
flag_id SERIAL PRIMARY KEY,
key VARCHAR NOT NULL UNIQUE,
rules JSON,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)