CREATE TABLE IF NOT EXISTS FLAGS(
flag_id SERIAL PRIMARY KEY NOT NULL,
key VARCHAR NOT NULL UNIQUE NOT NULL,
rules JSON NOT NULL,
created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
is_deleted BOOLEAN DEFAULT FALSE NOT NULL
)